pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/your-username/flask-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('flask-pipeline-app')
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    docker.image('flask-pipeline-app').run('-d -p 5000:5000 flask-pipeline')
                }
            }
        }
    }
}
